[package]
name = "navigation"
version = "0.1.0"
edition = "2024"

[dependencies]
pathfinding = "4.8.0"
json = "0.12.4"
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
futures = "0.3"